name: Build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup env
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm run build

      - name: Commit changes
        run: |
          author='${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>'
          message='Update build artifacts [skip ci]'

          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

          git commit --all --author "$author" --message "$message" || true

          git push
